apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
  namespace: homework
data:
  default.conf: |
    server {
      listen 8000;
      root /homework;
      index index.html;
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-controllers
  namespace: homework
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubernetes-controllers
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: kubernetes-controllers
    spec:
      nodeSelector:  # Ключевое добавление
        homework: "true"  # Pod будет запущен только на узлах с этой меткой
      containers:
        - name: webserver
          image: nginx:1.26.3
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: files
              mountPath: /homework
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
          lifecycle:
            preStop:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "nginx -s quit; while killall -0 nginx; do sleep 1; done; rm /homework/index.html"
          readinessProbe:
            exec:
              command:
                - "ls"
                - "/homework/index.html"
            initialDelaySeconds: 5
            periodSeconds: 5
      initContainers:
        - name: init
          image: busybox:1.28
          command:
            - "/bin/sh"
            - "-c"
            - "mkdir -p /init && echo '<!doctype html><title>kubernetes-controllers</title>' > /init/index.html"
          volumeMounts:
            - name: files
              mountPath: /init
      volumes:
        - name: files
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: nginx-conf
            optional: false